[tool.poetry]
name = "ice-launcher"
version = "0.1.0"
description = ""
authors = ["Manuel Quarneti <manuelquarneti@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
customtkinter = "^4.5.5"
Pillow = "^9.2.0"
requests = "^2.28.1"
minecraft-launcher-lib = {git = "https://gitlab.com/mq-1/minecraft-launcher-lib.git", branch = "secure-oauth2"}

[tool.poetry.dev-dependencies]
black = "^22.6.0"
pyinstaller = "^5.2"
mypy = "^0.961"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
